version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finlogic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-TU_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_NAME:-finlogic}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-TU_PASSWORD_DB}
    ports:
      - "${DB_PORT_EXTERNAL:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ../api
    container_name: finlogic_api
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-TU_PASSWORD_DB}
      DB_NAME: ${DB_NAME:-finlogic}
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET:-TU_SECRET_JWT}
    depends_on:
      - db
    volumes:
      - ../api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules

  app:
    build:
      context: ../app
    container_name: finlogic_app
    restart: always
    ports:
      - "${VITE_PORT:-8080}:8080"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    depends_on:
      - api
    volumes:
      - ../app:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules

volumes:
  db_data:
  app_node_modules:
  api_node_modules:
